### ISSUE TITLE
Problem with deletion of fsm model instances

### ISSUE THREAD

**Issue by francis-de-ladu** [viewflow/django-fsm#250]
I'm experiencing an issue that prevents me from deleting instances after their creation. The issue seems related to Django's deferred attributes since using the code from the December 9th, 2020 commit fixed it.

Here is the stack trace:
`Traceback (most recent call last):
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/base.py", line 946, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 297, in collect
    field.remote_field.on_delete(self, field, sub_objs, self.using)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 24, in CASCADE
    collector.collect(
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 295, in collect
    if sub_objs:
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/query.py", line 291, in __bool__
    self._fetch_all()
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/query.py", line 71, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/base.py", line 513, in from_db
    new = cls(*values)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django_fsm/__init__.py", line 449, in __init__
    self._update_initial_state()
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django_fsm/__init__.py", line 489, in _update_initial_state
    self.__initial_states = dict(
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django_fsm/__init__.py", line 490, in <genexpr>
    (field.attname, field.value_from_object(self)) for field in self.state_fields
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 933, in value_from_object
    return getattr(obj, self.attname)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django_fsm/__init__.py", line 231, in __get__
    return self.field.get_state(instance)
  File "/home/francis/Documents/djoser/backend/env/lib/python3.8/site-packages/django_fsm/__init__.py", line 271, in get_state
    return instance.__dict__[self.name]
KeyError: 'state'`

**Comment by em1208** [comment]
I'm having the same problem on delete but the latest master doesn't fix the issue.
```
  File "/Users/emassa/.pyenv/versions/connect/lib/python3.7/site-packages/django_fsm/__init__.py", line 231, in __get__
    return self.field.get_state(instance)
  File "/Users/emassa/.pyenv/versions/connect/lib/python3.7/site-packages/django_fsm/__init__.py", line 271, in get_state
    return instance.__dict__[self.name]
KeyError:
```

**Comment by kmmbvnr** [comment]
I can't reproduce the issue.. Could you please extend the tests to demonstrate it?

**Comment by andyi95** [comment]
I can suppose what's happening: you're trying to delete the same instance inside itself:
```
@transition(
        field=state,
        source=[STATE.STATE_CREATED, STATE.STATE_ACCEPTED],
        target=STATE.STATE_REJECTED,
        custom=dict(admin=True, button_name='Reject the object'))
    def reject(self):
        """Do something here..."""
        self.delete()
```
But the problem is that, Django FSM is trying to change the state after execution of method, so we get the error above. I would try to do the same using signals or deferred operations. Though, it would be much easier if Django-FSM could handle this "out-of-box"

**Comment by kmmbvnr** [comment]
So, if it's a delete call inside transition method, this is the limitation of django-fsm 2.0 design

I've just checked, it works well withing new version of fsm implementation - https://docs-next.viewflow.io/fsm/models.html
