### ISSUE TITLE
Can't create obj if use two FSMField in one model

### ISSUE THREAD

**Issue by depocoder** [viewflow/django-fsm#264]
When I trying create obj with two field FSMField and both field is protected, I get error

Traceback
```
Internal Server Error: /admin/library/book/add/
Traceback (most recent call last):
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1657, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1579, in _changeform_view
    form_validated = form.is_valid()
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/forms/forms.py", line 374, in full_clean
    self._post_clean()
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/forms/models.py", line 408, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, opts.exclude)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/forms/models.py", line 63, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 910, in save_form_data
    setattr(instance, self.name, data)
  File "/home/depocode/PycharmProjects/djangofsmbug/venv/lib/python3.9/site-packages/django_fsm/__init__.py", line 235, in __set__
    raise AttributeError('Direct {0} modification is not allowed'.format(self.field.name))
AttributeError: Direct create_progress modification is not allowed
```
example models.py

```python
from django.db import models
from django_fsm import FSMField


class Book(models.Model):
    class STATE:
        START = 'START'

    STATE_CHOICES = (
        (STATE.START, 'START', 'Book'),

    )

    class LOGIN_STATE:
        NO_LOGIN = 'NO_LOGIN'

    LOGIN_STATE_CHOICES = (
        (LOGIN_STATE.NO_LOGIN, 'NO_LOGIN', 'Book'),

    )
    login_status = FSMField(
        default=LOGIN_STATE.NO_LOGIN, state_choices=LOGIN_STATE_CHOICES,
        verbose_name='login status',
    )

    create_progress = FSMField(
        default=STATE.START, state_choices=STATE_CHOICES, protected=True,
        verbose_name='create progress',
    )

```

admin.py

```python
from django.contrib import admin

from library.models import Book


@admin.register(Book)
class AdminBook(admin.ModelAdmin):
    pass

```
pip freeze

```
asgiref==3.4.1
Django==3.2.6
django-fsm==2.7.1
pytz==2021.1
sqlparse==0.4.1
```

Python Version is 3.9

**Comment by kmmbvnr** [comment]
The test case with `.objects.create()` worked for me. For the admin, I think you need to declare those fields as `read_only`
