### ISSUE TITLE
graph_transitions raise exception > TypeError: requires_system_checks must be a list or tuple

### ISSUE THREAD

**Issue by mahmoud-ali** [viewflow/django-fsm#289]
Hi guys,

I am trying to graph transitions and I encountered this **TypeError: requires_system_checks must be a list or tuple.**
Any help?

    Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
    Django 4.1
    Graphviz 0.20.1

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "E:\mahmoud\django\workflow\env\lib\site-packages\django\core\management\
__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "E:\mahmoud\django\workflow\env\lib\site-packages\django\core\management\
__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\mahmoud\django\workflow\env\lib\site-packages\django\core\management\
__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "E:\mahmoud\django\workflow\env\lib\site-packages\django\core\management\
__init__.py", line 49, in load_command_class
    return module.Command()
  File "E:\mahmoud\django\workflow\env\lib\site-packages\django\core\management\
base.py", line 274, in __init__
    raise TypeError("requires_system_checks must be a list or tuple.")
TypeError: requires_system_checks must be a list or tuple.

**Comment by neilmb** [comment]
I too am using Django 4.1 and would love to be able to use `django-fsm` `graph_transitions` command. Can the proposed fix be merged and a new release made?

**Comment by pfouque** [comment]
Hi @neilmb ,
If you really need it before it's merged, you can override the command by copying the whole file into your project:
https://docs.djangoproject.com/en/4.1/howto/custom-management-commands/#overriding-commands
:)

**Comment by virogenesis** [comment]
Sorta related MR https://github.com/viewflow/django-fsm/pull/293

**Comment by kmmbvnr** [comment]
Merged #293

**Comment by dwhu** [comment]
Whats the timeline for this to be released?

**Comment by Borhink** [comment]
I still have this error. I'm using :
Python 3.10.13
Django 4.2.4
graphviz 0.20.1

ERROR :
Traceback (most recent call last):
  File "/mnt/c/Users/hidden/manage.py", line 22, in <module>
    main()
  File "/mnt/c/Users/hidden/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/mnt/c/Users/hidden/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/mnt/c/Users/hidden/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/c/Users/hidden/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 275, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/mnt/c/Users/hidden/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 49, in load_command_class
    return module.Command()
  File "/mnt/c/Users/hidden/venv/lib/python3.10/site-packages/django/core/management/base.py", line 284, in __init__
    raise TypeError("requires_system_checks must be a list or tuple.")
TypeError: requires_system_checks must be a list or tuple.
