### ISSUE TITLE
django_fsm.TransitionNotAllowed

### ISSUE THREAD

**Issue by achillis2** [viewflow/django-fsm#294]
Why do I get the error below when I tried to do the transition?  Is this a bug? Thanks

```
>>> t = Task.objects.first()
>>> t.state
"(0, 'Open')"
>>> t.to_in_progress()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/dingli/projects/personal/django_history_fsm_guardian/lib/python3.11/site-packages/django_fsm/__init__.py", line 573, in _change_state
    return fsm_meta.field.change_state(instance, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dingli/projects/personal/django_history_fsm_guardian/lib/python3.11/site-packages/django_fsm/__init__.py", line 339, in change_state
    raise TransitionNotAllowed(
django_fsm.TransitionNotAllowed: Can't switch from state '(0, 'Open')' using method 'to_in_progress'
```

Here is the model.
```python
STATES = ('Open', 'In Progress', 'Resolved', 'Re Opened', 'Closed')
STATES = list(enumerate(STATES))
              
class Task(models.Model):
    title = models.CharField(max_length=100, null=False)
    description = models.TextField()
    state = FSMField(default=STATES[0], choices=STATES)

    def __str__(self):
        return f'{self.title}: {self.description}'
    
    @transition(field=state, source=['Open', 'Re Opened'], target='In Progress')
    def to_in_progress(self):
        pass

    @transition(field=state, source='In Progress', target='Resolved')
    def to_resolved(self):
        pass
```

**Comment by kmmbvnr** [comment]
Seems like caused by you database content 

Looks like somehow you saved wrong value inside state field
